# Generated by Django 4.2.11 on 2025-10-22 15:42

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_enable_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount_type",
            field=models.CharField(
                choices=[("FIXED", "Fixed Amount"), ("PERCENTAGE", "Percentage")],
                default="FIXED",
                help_text="Type of discount applied",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Original discount value (percentage or fixed amount)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
