# Generated by Django 4.2.11 on 2025-10-23 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0003_add_discount_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User currently assigned to this terminal (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_terminals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
