# Generated by Django 4.2.11 on 2025-10-30 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_giftcardtransaction"),
        ("sales", "0004_add_terminal_user_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer who made the purchase (optional for walk-in sales)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="crm.customer",
            ),
        ),
    ]
