repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: black (via docker)
        entry: docker compose exec -T web black
        language: system
        types: [python]
        args: ['--check', '--line-length=100']
        
      - id: isort
        name: isort (via docker)
        entry: docker compose exec -T web isort
        language: system
        types: [python]
        args: ['--check-only', '--profile', 'black', '--line-length', '100']
        
      - id: flake8
        name: flake8 (via docker)
        entry: docker compose exec -T web flake8
        language: system
        types: [python]
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']
