#!/usr/bin/env python3
"""
Translate authentication pages, forms, and UI strings
"""
import re

# Authentication and user interface translations
TRANSLATIONS = {
    # Login page
    "Sign in to your jewelry shop account": "ورود به حساب جواهرفروشی شما",
    "Sign in with": "ورود با",
    "Continue with Google": "ادامه با گوگل",
    "Continue with GitHub": "ادامه با گیت‌هاب",
    "Continue with Facebook": "ادامه با فیسبوک",
    "Or continue with": "یا ادامه با",
    "Username or Email": "نام کاربری یا ایمیل",
    "Enter your username or email": "نام کاربری یا ایمیل خود را وارد کنید",
    "Enter your password": "رمز عبور خود را وارد کنید",
    "Don't have an account?": "حساب کاربری ندارید؟",
    "Sign up": "ثبت‌نام",
    "All rights reserved.": "تمامی حقوق محفوظ است.",
    
    # Registration page
    "Create Account": "ایجاد حساب کاربری",
    "Join our jewelry shop platform": "به پلتفرم جواهرفروشی ما بپیوندید",
    "Choose a username": "یک نام کاربری انتخاب کنید",
    "Enter your email address": "آدرس ایمیل خود را وارد کنید",
    "Create a strong password": "یک رمز عبور قوی ایجاد کنید",
    "Minimum 12 characters": "حداقل 12 کاراکتر",
    "Confirm your password": "رمز عبور خود را تأیید کنید",
    "Already have an account?": "قبلاً حساب کاربری دارید؟",
    "Sign in": "ورود",
    
    # Admin login
    "Secure administrator access only": "فقط دسترسی امن مدیر",
    "Login Failed": "ورود ناموفق",
    "Restricted Access": "دسترسی محدود",
    "Enter your admin username": "نام کاربری مدیر خود را وارد کنید",
    "Enter your admin password": "رمز عبور مدیر خود را وارد کنید",
    "Sign In Securely": "ورود امن",
    "Are you a tenant user?": "کاربر مستأجر هستید؟",
    "Go to Tenant Login": "به ورود مستأجر بروید",
    "Protected by advanced security measures": "محافظت شده توسط اقدامات امنیتی پیشرفته",
    
    # Password reset
    "Reset Password": "بازیابی رمز عبور",
    "Forgot your password?": "رمز عبور خود را فراموش کرده‌اید؟",
    "Enter your email to reset": "ایمیل خود را برای بازیابی وارد کنید",
    "Send Reset Link": "ارسال لینک بازیابی",
    "Back to login": "بازگشت به ورود",
    "Check your email": "ایمیل خود را بررسی کنید",
    "Reset link sent": "لینک بازیابی ارسال شد",
    "New Password": "رمز عبور جدید",
    "Set new password": "تنظیم رمز عبور جدید",
    "Password changed successfully": "رمز عبور با موفقیت تغییر یافت",
    
    # Validation messages
    "This field is required": "این فیلد الزامی است",
    "Invalid email address": "آدرس ایمیل نامعتبر",
    "Password is too weak": "رمز عبور خیلی ضعیف است",
    "Passwords do not match": "رمزهای عبور مطابقت ندارند",
    "Username already exists": "نام کاربری قبلاً وجود دارد",
    "Email already registered": "ایمیل قبلاً ثبت شده است",
    "Invalid credentials": "اعتبارنامه نامعتبر",
    "Account is disabled": "حساب کاربری غیرفعال است",
    "Account is locked": "حساب کاربری قفل شده است",
    "Too many login attempts": "تلاش‌های ورود بیش از حد",
    
    # Common form labels
    "Username": "نام کاربری",
    "Email Address": "آدرس ایمیل",
    "Password": "رمز عبور",
    "Confirm Password": "تأیید رمز عبور",
    "Current Password": "رمز عبور فعلی",
    "First Name": "نام",
    "Last Name": "نام خانوادگی",
    "Full Name": "نام کامل",
    "Phone Number": "شماره تلفن",
    "Date of Birth": "تاریخ تولد",
    "Gender": "جنسیت",
    "Male": "مرد",
    "Female": "زن",
    "Other": "سایر",
    "Address": "آدرس",
    "City": "شهر",
    "State": "استان",
    "Country": "کشور",
    "Postal Code": "کد پستی",
    "ZIP Code": "کد ZIP",
    
    # Common buttons
    "Submit": "ارسال",
    "Cancel": "لغو",
    "Save": "ذخیره",
    "Save Changes": "ذخیره تغییرات",
    "Delete": "حذف",
    "Remove": "حذف",
    "Add": "افزودن",
    "Create": "ایجاد",
    "Update": "به‌روزرسانی",
    "Edit": "ویرایش",
    "View": "مشاهده",
    "Back": "بازگشت",
    "Next": "بعدی",
    "Previous": "قبلی",
    "Continue": "ادامه",
    "Finish": "پایان",
    "Close": "بستن",
    "Open": "باز کردن",
    "Show": "نمایش",
    "Hide": "مخفی کردن",
    "Expand": "گسترش",
    "Collapse": "جمع کردن",
    "Minimize": "کوچک کردن",
    "Maximize": "بزرگ کردن",
    "Download": "دانلود",
    "Upload": "آپلود",
    "Print": "چاپ",
    "Share": "اشتراک‌گذاری",
    "Copy": "کپی",
    "Paste": "چسباندن",
    "Cut": "برش",
    "Undo": "واگرد",
    "Redo": "بازگرد",
    "Select": "انتخاب",
    "Select All": "انتخاب همه",
    "Deselect": "لغو انتخاب",
    "Clear": "پاک کردن",
    "Reset": "بازنشانی",
    "Refresh": "تازه‌سازی",
    "Reload": "بارگیری مجدد",
    "Apply": "اعمال",
    "Confirm": "تأیید",
    "Approve": "تأیید",
    "Reject": "رد",
    "Send": "ارسال",
    "Receive": "دریافت",
    "Reply": "پاسخ",
    "Forward": "ارسال به دیگران",
    "Attach": "پیوست",
    "Detach": "جداسازی",
    "Link": "لینک",
    "Unlink": "لغو لینک",
    
    # Status messages
    "Success": "موفق",
    "Error": "خطا",
    "Warning": "هشدار",
    "Info": "اطلاعات",
    "Loading": "در حال بارگیری",
    "Processing": "در حال پردازش",
    "Saving": "در حال ذخیره",
    "Deleting": "در حال حذف",
    "Uploading": "در حال آپلود",
    "Downloading": "در حال دانلود",
    "Please wait": "لطفاً صبر کنید",
    "Operation completed": "عملیات تکمیل شد",
    "Operation failed": "عملیات ناموفق بود",
    "No data": "داده‌ای وجود ندارد",
    "No results found": "نتیجه‌ای یافت نشد",
    "No items to display": "موردی برای نمایش وجود ندارد",
    "Empty list": "لیست خالی",
    
    # Time and date
    "Today": "امروز",
    "Yesterday": "دیروز",
    "Tomorrow": "فردا",
    "This week": "این هفته",
    "Last week": "هفته گذشته",
    "Next week": "هفته آینده",
    "This month": "این ماه",
    "Last month": "ماه گذشته",
    "Next month": "ماه آینده",
    "This year": "امسال",
    "Last year": "سال گذشته",
    "Next year": "سال آینده",
    "Now": "اکنون",
    "Just now": "همین الان",
    "A moment ago": "لحظاتی پیش",
    "Minutes ago": "دقیقه‌ای پیش",
    "Hours ago": "ساعتی پیش",
    "Days ago": "روزی پیش",
    "Weeks ago": "هفته‌ای پیش",
    "Months ago": "ماهی پیش",
    "Years ago": "سالی پیش",
    
    # Navigation
    "Home": "خانه",
    "Dashboard": "داشبورد",
    "Profile": "پروفایل",
    "Settings": "تنظیمات",
    "Preferences": "ترجیحات",
    "Account": "حساب",
    "Help": "راهنما",
    "Support": "پشتیبانی",
    "About": "درباره",
    "Contact": "تماس",
    "Privacy": "حریم خصوصی",
    "Terms": "شرایط",
    "FAQ": "سؤالات متداول",
    "Documentation": "مستندات",
    "API": "API",
    "Developers": "توسعه‌دهندگان",
    "Blog": "بلاگ",
    "News": "اخبار",
    "Updates": "به‌روزرسانی‌ها",
    "Changelog": "تغییرات",
    "Releases": "نسخه‌ها",
    "Version": "نسخه",
    "Status": "وضعیت",
    "Health": "سلامت",
    "System": "سیستم",
    "Admin": "مدیر",
    "Administrator": "مدیر سیستم",
    "Moderator": "ناظر",
    "User": "کاربر",
    "Guest": "مهمان",
    "Member": "عضو",
    "Subscriber": "مشترک",
    "Customer": "مشتری",
    "Client": "مشتری",
    "Partner": "شریک",
    "Vendor": "فروشنده",
    "Supplier": "تأمین‌کننده",
    "Provider": "ارائه‌دهنده",
    
    # Notifications
    "Notifications": "اعلان‌ها",
    "Alerts": "هشدارها",
    "Messages": "پیام‌ها",
    "Inbox": "صندوق ورودی",
    "Outbox": "صندوق خروجی",
    "Sent": "ارسال شده",
    "Drafts": "پیش‌نویس‌ها",
    "Trash": "سطل زباله",
    "Spam": "هرزنامه",
    "Archive": "بایگانی",
    "Starred": "ستاره‌دار",
    "Important": "مهم",
    "Unread": "خوانده نشده",
    "Read": "خوانده شده",
    "Mark as read": "علامت‌گذاری به عنوان خوانده شده",
    "Mark as unread": "علامت‌گذاری به عنوان خوانده نشده",
    "Mark all as read": "علامت‌گذاری همه به عنوان خوانده شده",
    "Delete all": "حذف همه",
    "Clear all": "پاک کردن همه",
    
    # Pagination
    "Page": "صفحه",
    "of": "از",
    "First": "اولین",
    "Last": "آخرین",
    "Showing": "نمایش",
    "to": "تا",
    "entries": "مورد",
    "items": "آیتم",
    "results": "نتیجه",
    "per page": "در هر صفحه",
    "Go to page": "برو به صفحه",
    "Items per page": "آیتم در هر صفحه",
    
    # Filters and sorting
    "Filter": "فیلتر",
    "Filters": "فیلترها",
    "Sort": "مرتب‌سازی",
    "Search": "جستجو",
    "Find": "یافتن",
    "Query": "پرس‌وجو",
    "Advanced search": "جستجوی پیشرفته",
    "Quick search": "جستجوی سریع",
    "Clear filters": "پاک کردن فیلترها",
    "Reset filters": "بازنشانی فیلترها",
    "Apply filters": "اعمال فیلترها",
    "Sort ascending": "مرتب‌سازی صعودی",
    "Sort descending": "مرتب‌سازی نزولی",
    "Default sort": "مرتب‌سازی پیش‌فرض",
    
    # File operations
    "File": "فایل",
    "Files": "فایل‌ها",
    "Folder": "پوشه",
    "Directory": "دایرکتوری",
    "Upload file": "آپلود فایل",
    "Choose file": "انتخاب فایل",
    "Select file": "انتخاب فایل",
    "Drop file here": "فایل را اینجا رها کنید",
    "Drag and drop": "بکشید و رها کنید",
    "Browse": "مرور",
    "Attachment": "پیوست",
    "Attachments": "پیوست‌ها",
    "Download file": "دانلود فایل",
    "Delete file": "حذف فایل",
    "File name": "نام فایل",
    "File size": "حجم فایل",
    "File type": "نوع فایل",
    "File format": "قالب فایل",
    "Last modified": "آخرین تغییر",
    "Created by": "ایجاد شده توسط",
    "Modified by": "تغییر شده توسط",
    "Owner": "مالک",
    "Permissions": "مجوزها",
    "Access": "دسترسی",
    "Visibility": "قابلیت دید",
    "Public": "عمومی",
    "Private": "خصوصی",
    "Shared": "اشتراک‌گذاری شده",
    "Restricted": "محدود شده",
}


def update_po_auth(filepath):
    """Apply authentication and UI translations."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    translated = 0
    for en, fa in TRANSLATIONS.items():
        esc = re.escape(en)
        pattern = rf'(msgid "{esc}"\nmsgstr ")(")'
        new, count = re.subn(pattern, rf'\1{fa}\2', content)
        if count:
            content = new
            translated += count

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    return translated

if __name__ == '__main__':
    po = 'locale/fa/LC_MESSAGES/django.po'
    print('Translating authentication pages and common UI strings...')
    count = update_po_auth(po)
    print(f'✅ Translated {count} entries')
    print(f'Progress: 367 + {count} = {367 + count} total translations')
