# Generated by Django 4.2.11 on 2025-10-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_supplierdocument_suppliercommunication"),
    ]

    operations = [
        # Enable RLS on new procurement tables
        migrations.RunSQL(
            sql="ALTER TABLE procurement_supplier_communications ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE procurement_supplier_communications DISABLE ROW LEVEL SECURITY;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE procurement_supplier_documents ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE procurement_supplier_documents DISABLE ROW LEVEL SECURITY;"
        ),
        
        # Create RLS policies for supplier communications (via supplier)
        migrations.RunSQL(
            sql="""
            CREATE POLICY tenant_isolation_policy ON procurement_supplier_communications
                USING (
                    supplier_id IN (
                        SELECT id FROM procurement_suppliers 
                        WHERE tenant_id = current_setting('app.current_tenant')::uuid
                    )
                );
            """,
            reverse_sql="DROP POLICY IF EXISTS tenant_isolation_policy ON procurement_supplier_communications;"
        ),
        
        # Create RLS policies for supplier documents (via supplier)
        migrations.RunSQL(
            sql="""
            CREATE POLICY tenant_isolation_policy ON procurement_supplier_documents
                USING (
                    supplier_id IN (
                        SELECT id FROM procurement_suppliers 
                        WHERE tenant_id = current_setting('app.current_tenant')::uuid
                    )
                );
            """,
            reverse_sql="DROP POLICY IF EXISTS tenant_isolation_policy ON procurement_supplier_documents;"
        ),
    ]
