# Generated by Django 4.2.11 on 2025-10-23 14:24

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_branch_manager_branch_opening_hours"),
        ("procurement", "0004_auto_20251023_1346"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderApprovalThreshold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum amount for this approval level",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount for this approval level (null = no limit)",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        choices=[
                            ("TENANT_EMPLOYEE", "Any Employee"),
                            ("TENANT_MANAGER", "Manager or Above"),
                            ("TENANT_OWNER", "Owner Only"),
                        ],
                        default="TENANT_MANAGER",
                        help_text="Minimum role required to approve at this level",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this threshold is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_approval_thresholds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this approval threshold",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_approval_thresholds",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_approval_thresholds",
                "ordering": ["min_amount"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="procurement_tenant__399aed_idx"
                    ),
                    models.Index(
                        fields=["min_amount", "max_amount"], name="procurement_min_amo_9af8e2_idx"
                    ),
                ],
            },
        ),
    ]
