# Generated by Django 4.2.11 on 2025-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0006_add_goods_receipt_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="default_expense_account",
            field=models.CharField(
                blank=True,
                help_text="Default GL account code for expenses from this supplier",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_1099_vendor",
            field=models.BooleanField(
                default=False, help_text="Whether this supplier requires 1099 tax reporting"
            ),
        ),
    ]
