# Generated by Django 4.2.11 on 2025-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0007_add_accounting_fields_to_supplier"),
    ]

    operations = [
        # Remove the old FK field if it exists
        migrations.RunSQL(
            sql="ALTER TABLE procurement_suppliers DROP COLUMN IF EXISTS default_expense_account_id CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        # Add the new CharField field
        migrations.AddField(
            model_name="supplier",
            name="default_expense_account",
            field=models.CharField(
                blank=True,
                help_text="Default GL account code for expenses from this supplier",
                max_length=20,
            ),
        ),
    ]
