# Generated by Django 4.2.11 on 2025-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0007_add_accounting_fields_to_supplier"),
    ]

    operations = [
        # Remove the old FK field if it exists (from a previous version)
        # The CharField was already added in migration 0007
        migrations.RunSQL(
            sql="ALTER TABLE procurement_suppliers DROP COLUMN IF EXISTS default_expense_account_id CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
    ]
