# Generated by Django 4.2.11 on 2025-10-21 15:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the tenant",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(help_text="Name of the jewelry shop business", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the tenant",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("PENDING_DELETION", "Pending Deletion"),
                        ],
                        default="ACTIVE",
                        help_text="Current operational status of the tenant",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the tenant was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the tenant was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="tenant_status_idx"),
                    models.Index(fields=["slug"], name="tenant_slug_idx"),
                ],
            },
        ),
    ]
