# Generated by Django 4.2.11 on 2025-10-21 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_disable_tenants_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ROLE_CHANGED", "Role Changed"),
                            ("PERMISSION_GRANTED", "Permission Granted"),
                            ("PERMISSION_REVOKED", "Permission Revoked"),
                            ("GROUP_ADDED", "Group Added"),
                            ("GROUP_REMOVED", "Group Removed"),
                            ("BRANCH_ASSIGNED", "Branch Assigned"),
                            ("BRANCH_UNASSIGNED", "Branch Unassigned"),
                        ],
                        help_text="Type of permission change",
                        max_length=50,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, help_text="Previous value (JSON format)"),
                ),
                ("new_value", models.TextField(blank=True, help_text="New value (JSON format)")),
                (
                    "description",
                    models.TextField(help_text="Human-readable description of the change"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string of the actor"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When the change occurred"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="User whose permissions were changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Audit Log",
                "verbose_name_plural": "Permission Audit Logs",
                "db_table": "permission_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["target_user", "-timestamp"], name="audit_user_time_idx"),
                    models.Index(fields=["actor", "-timestamp"], name="audit_actor_time_idx"),
                    models.Index(fields=["action", "-timestamp"], name="audit_action_time_idx"),
                ],
            },
        ),
    ]
