# Generated by Django 4.2.11 on 2025-10-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ensure_tenants_rls_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch manager (must be a user from the same tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="opening_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Branch opening hours (e.g., {'monday': '9:00-18:00', 'tuesday': '9:00-18:00', ...})",
            ),
        ),
    ]
