# Generated by Django 4.2.11 on 2025-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_data_management_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="deletion_grace_period_days",
            field=models.IntegerField(
                default=30, help_text="Number of days before permanent deletion after scheduling"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="scheduled_deletion_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the tenant is scheduled for deletion",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when the tenant was suspended", null=True
            ),
        ),
    ]
