# Generated by Django 4.2.11 on 2025-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_announcement_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="request_query_params",
            field=models.TextField(
                blank=True, db_index=True, help_text="Request path/URL", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HTTP request method (GET, POST, PUT, DELETE, etc.)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(
                blank=True, default="", help_text="HTTP request path", max_length=500
            ),
        ),
    ]
