# Generated by Django 4.2.11 on 2025-10-28 10:22

from django.db import migrations


def set_defaults_for_existing_records(apps, schema_editor):
    """Set default values for existing NULL records."""
    AuditLog = apps.get_model("core", "AuditLog")
    
    # Update any NULL request_method to empty string
    AuditLog.objects.filter(request_method__isnull=True).update(request_method="")
    
    # Update any NULL request_path to empty string  
    AuditLog.objects.filter(request_path__isnull=True).update(request_path="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_default_to_audit_fields"),
    ]

    operations = [
        migrations.RunPython(set_defaults_for_existing_records, migrations.RunPython.noop),
        # Set database-level defaults
        migrations.RunSQL(
            sql="ALTER TABLE audit_logs ALTER COLUMN request_method SET DEFAULT '';",
            reverse_sql="ALTER TABLE audit_logs ALTER COLUMN request_method DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE audit_logs ALTER COLUMN request_path SET DEFAULT '';",
            reverse_sql="ALTER TABLE audit_logs ALTER COLUMN request_path DROP DEFAULT;",
        ),
    ]
