# Generated by Django 4.2.11 on 2025-10-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_fix_audit_log_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="request_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HTTP request method (GET, POST, PUT, DELETE, etc.)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(
                blank=True, default="", help_text="HTTP request path", max_length=500, null=True
            ),
        ),
    ]
