# Generated by Django 4.2.11 on 2025-10-28 12:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_make_audit_fields_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the webhook",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Descriptive name for the webhook", max_length=255),
                ),
                (
                    "url",
                    models.URLField(help_text="Target URL for webhook delivery", max_length=500),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of webhook purpose"
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of event types this webhook subscribes to"
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="HMAC secret for payload signing (auto-generated)", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the webhook is active and should receive events",
                    ),
                ),
                (
                    "consecutive_failures",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive delivery failures"
                    ),
                ),
                (
                    "last_failure_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of last delivery failure", null=True
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of last successful delivery", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the webhook was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the webhook was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this webhook",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this webhook",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the delivery",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of event that triggered this delivery", max_length=100
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        help_text="ID of the event object (e.g., sale ID, inventory ID)"
                    ),
                ),
                ("payload", models.JSONField(help_text="JSON payload sent to webhook URL")),
                (
                    "signature",
                    models.CharField(help_text="HMAC signature of the payload", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        default="PENDING",
                        help_text="Current delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, help_text="Number of delivery attempts made"),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=5, help_text="Maximum number of delivery attempts"),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled time for next retry attempt", null=True
                    ),
                ),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True, help_text="HTTP status code from webhook endpoint", null=True
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True,
                        help_text="Response body from webhook endpoint (truncated to 10KB)",
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True, default=dict, help_text="Response headers from webhook endpoint"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if delivery failed"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the delivery was sent", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the delivery was completed (success or final failure)",
                        null=True,
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, help_text="Delivery duration in milliseconds", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the delivery was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the delivery was last updated"
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        help_text="Webhook that this delivery belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "-created_at"], name="delivery_webhook_created_idx"
                    ),
                    models.Index(fields=["webhook", "status"], name="delivery_webhook_status_idx"),
                    models.Index(fields=["status", "next_retry_at"], name="delivery_retry_idx"),
                    models.Index(fields=["event_type", "event_id"], name="delivery_event_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["tenant", "is_active"], name="webhook_tenant_active_idx"),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["tenant", "-created_at"], name="webhook_tenant_created_idx"),
        ),
    ]
