# Generated by Django 4.2.11 on 2025-10-28 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_job_monitoring_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Unique schedule name", max_length=255, unique=True),
                ),
                (
                    "task_name",
                    models.CharField(db_index=True, help_text="Celery task name", max_length=255),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("cron", "Cron Expression"), ("interval", "Interval")],
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression (e.g., '0 2 * * *')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "interval_value",
                    models.IntegerField(blank=True, help_text="Interval value", null=True),
                ),
                (
                    "interval_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("seconds", "Seconds"),
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        help_text="Interval unit",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("args", models.JSONField(blank=True, default=list, help_text="Task arguments")),
                (
                    "kwargs",
                    models.JSONField(blank=True, default=dict, help_text="Task keyword arguments"),
                ),
                (
                    "queue",
                    models.CharField(default="default", help_text="Queue name", max_length=100),
                ),
                ("priority", models.IntegerField(default=5, help_text="Priority (0-10)")),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Enable or disable this schedule"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, help_text="Last execution time", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_schedules",
                "ordering": ["name"],
            },
        ),
    ]
