# Generated by Django 4.2.11 on 2025-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_job_schedule_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobexecution",
            name="cpu_percent",
            field=models.FloatField(
                blank=True, help_text="CPU usage percentage during execution", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="memory_mb",
            field=models.FloatField(
                blank=True, help_text="Memory usage in MB during execution", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="peak_memory_mb",
            field=models.FloatField(blank=True, help_text="Peak memory usage in MB", null=True),
        ),
        migrations.AddField(
            model_name="jobstatistics",
            name="peak_cpu_percent",
            field=models.FloatField(blank=True, help_text="Peak CPU usage percentage", null=True),
        ),
        migrations.AddField(
            model_name="jobstatistics",
            name="peak_memory_mb",
            field=models.FloatField(blank=True, help_text="Peak memory usage in MB", null=True),
        ),
        migrations.AlterField(
            model_name="jobstatistics",
            name="avg_cpu_percent",
            field=models.FloatField(
                blank=True, help_text="Average CPU usage percentage", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobstatistics",
            name="avg_memory_mb",
            field=models.FloatField(blank=True, help_text="Average memory usage in MB", null=True),
        ),
    ]
