# Generated by Django 4.2.11 on 2025-11-06 16:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretsKeyRotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the key rotation",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rotation_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the rotation was initiated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when the rotation was completed", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="INITIATED",
                        help_text="Current status of the key rotation",
                        max_length=20,
                    ),
                ),
                (
                    "old_key_fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the old key (for verification)",
                        max_length=64,
                    ),
                ),
                (
                    "new_key_fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the new key (for verification)",
                        max_length=64,
                    ),
                ),
                (
                    "rotation_reason",
                    models.TextField(
                        help_text="Reason for key rotation (scheduled, security incident, etc.)"
                    ),
                ),
                (
                    "files_re_encrypted",
                    models.JSONField(
                        default=list,
                        help_text="List of files that were re-encrypted with the new key",
                    ),
                ),
                (
                    "backup_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to backup of old encrypted files",
                        max_length=500,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if rotation failed"),
                ),
                (
                    "verification_passed",
                    models.BooleanField(
                        default=False, help_text="Whether post-rotation verification passed"
                    ),
                ),
                (
                    "verification_details",
                    models.JSONField(
                        default=dict, help_text="Details of verification checks performed"
                    ),
                ),
                (
                    "next_rotation_due",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when next rotation is due (90 days from completion)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes about this rotation"),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the key rotation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="key_rotations_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secrets Key Rotation",
                "verbose_name_plural": "Secrets Key Rotations",
                "db_table": "secrets_key_rotations",
                "ordering": ["-rotation_date"],
                "indexes": [
                    models.Index(fields=["-rotation_date"], name="key_rotation_date_idx"),
                    models.Index(fields=["status"], name="key_rotation_status_idx"),
                    models.Index(fields=["next_rotation_due"], name="key_rotation_next_due_idx"),
                ],
            },
        ),
    ]
