# Generated by Django 4.2.26 on 2025-12-07 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_add_secrets_key_rotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the domain",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain_type",
                    models.CharField(
                        choices=[("SUBDOMAIN", "Subdomain"), ("CUSTOM", "Custom Domain")],
                        help_text="Type of domain (subdomain or custom)",
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Full domain name (e.g., shop.jewelry-shop.local or custom.example.com)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the primary domain for the tenant"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="DNS verification status for custom domains",
                        max_length=20,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, help_text="Token for DNS TXT record verification", max_length=64
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when domain was verified", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Domain",
                "verbose_name_plural": "Tenant Domains",
                "db_table": "tenant_domains",
                "ordering": ["-is_primary", "domain"],
                "indexes": [
                    models.Index(fields=["tenant", "is_primary"], name="domain_tenant_primary_idx"),
                    models.Index(fields=["domain"], name="domain_lookup_idx"),
                    models.Index(fields=["verification_status"], name="domain_verification_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TemporaryPassword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the temporary password",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Hashed temporary password (Django password hash format)",
                        max_length=128,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Timestamp when this temporary password expires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this temporary password was used",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin who created this temporary password",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_temp_passwords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this temporary password is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_passwords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporary Password",
                "verbose_name_plural": "Temporary Passwords",
                "db_table": "temporary_passwords",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="temp_pwd_user_idx"),
                    models.Index(fields=["expires_at"], name="temp_pwd_expiry_idx"),
                ],
            },
        ),
    ]
