# Generated by Django 4.2.11 on 2025-10-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_ledger", "0016_remove_accountmodel_django_ledg_coa_mod_e19964_idx_and_more"),
        ("core", "0008_branch_manager_branch_opening_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="JewelryChartOfAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash and Cash Equivalents"),
                            ("INVENTORY", "Inventory"),
                            ("ACCOUNTS_RECEIVABLE", "Accounts Receivable"),
                            ("EQUIPMENT", "Equipment and Fixtures"),
                            ("PREPAID_EXPENSES", "Prepaid Expenses"),
                            ("ACCOUNTS_PAYABLE", "Accounts Payable"),
                            ("ACCRUED_EXPENSES", "Accrued Expenses"),
                            ("LOANS_PAYABLE", "Loans Payable"),
                            ("SALES_TAX_PAYABLE", "Sales Tax Payable"),
                            ("OWNERS_EQUITY", "Owner's Equity"),
                            ("RETAINED_EARNINGS", "Retained Earnings"),
                            ("JEWELRY_SALES", "Jewelry Sales"),
                            ("REPAIR_REVENUE", "Repair Services Revenue"),
                            ("CUSTOM_ORDER_REVENUE", "Custom Order Revenue"),
                            ("GIFT_CARD_REVENUE", "Gift Card Revenue"),
                            ("COST_OF_GOODS_SOLD", "Cost of Goods Sold"),
                            ("RENT_EXPENSE", "Rent Expense"),
                            ("UTILITIES_EXPENSE", "Utilities Expense"),
                            ("INSURANCE_EXPENSE", "Insurance Expense"),
                            ("MARKETING_EXPENSE", "Marketing Expense"),
                            ("EMPLOYEE_WAGES", "Employee Wages"),
                            ("PROFESSIONAL_FEES", "Professional Fees"),
                            ("BANK_FEES", "Bank Fees"),
                            ("DEPRECIATION_EXPENSE", "Depreciation Expense"),
                        ],
                        max_length=50,
                    ),
                ),
                ("account_code", models.CharField(max_length=20, unique=True)),
                ("parent_code", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chart of Accounts Template",
                "verbose_name_plural": "Chart of Accounts Templates",
                "db_table": "accounting_chart_template",
                "ordering": ["account_code"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("CASH_SALE", "Cash Sale"),
                            ("CARD_SALE", "Card Sale"),
                            ("INVENTORY_PURCHASE", "Inventory Purchase"),
                            ("REPAIR_REVENUE", "Repair Service Revenue"),
                            ("CUSTOM_ORDER", "Custom Order"),
                            ("EXPENSE_PAYMENT", "Expense Payment"),
                            ("LOAN_PAYMENT", "Loan Payment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Journal Entry Template",
                "verbose_name_plural": "Journal Entry Templates",
                "db_table": "accounting_journal_templates",
            },
        ),
        migrations.CreateModel(
            name="JournalEntryTemplateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_code", models.CharField(max_length=20)),
                (
                    "debit_credit",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=6
                    ),
                ),
                (
                    "amount_field",
                    models.CharField(
                        help_text="Field name from source transaction (e.g., 'total', 'tax', 'subtotal')",
                        max_length=50,
                    ),
                ),
                (
                    "description_template",
                    models.CharField(
                        help_text="Template for line description (e.g., 'Sale #{sale_number}')",
                        max_length=200,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentrytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry Template Line",
                "verbose_name_plural": "Journal Entry Template Lines",
                "db_table": "accounting_journal_template_lines",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JewelryEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fiscal_year_start_month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        default=1,
                        help_text="Month when fiscal year starts (1=January, 4=April, etc.)",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="USD", help_text="Default currency for this entity", max_length=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ledger_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_entity",
                        to="django_ledger.entitymodel",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_entity",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Entity",
                "verbose_name_plural": "Jewelry Entities",
                "db_table": "accounting_jewelry_entity",
            },
        ),
        migrations.CreateModel(
            name="AccountingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "default_cash_account",
                    models.CharField(
                        default="1001",
                        help_text="Default cash account for cash sales",
                        max_length=20,
                    ),
                ),
                (
                    "default_card_account",
                    models.CharField(
                        default="1002", help_text="Default account for card payments", max_length=20
                    ),
                ),
                (
                    "default_inventory_account",
                    models.CharField(
                        default="1200", help_text="Default inventory asset account", max_length=20
                    ),
                ),
                (
                    "default_cogs_account",
                    models.CharField(
                        default="5001",
                        help_text="Default cost of goods sold account",
                        max_length=20,
                    ),
                ),
                (
                    "default_sales_account",
                    models.CharField(
                        default="4001", help_text="Default sales revenue account", max_length=20
                    ),
                ),
                (
                    "default_tax_account",
                    models.CharField(
                        default="2003", help_text="Default sales tax payable account", max_length=20
                    ),
                ),
                (
                    "use_automatic_journal_entries",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create journal entries for sales and purchases",
                    ),
                ),
                (
                    "inventory_valuation_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In, First Out"),
                            ("LIFO", "Last In, First Out"),
                            ("WEIGHTED_AVG", "Weighted Average"),
                        ],
                        default="FIFO",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_config",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Configuration",
                "verbose_name_plural": "Accounting Configurations",
                "db_table": "accounting_configuration",
            },
        ),
    ]
