# Generated by Django 4.2.11 on 2025-10-22 22:03

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_branch_manager_branch_opening_hours"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(help_text="Expense description", max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("UTILITIES", "Utilities"),
                            ("INSURANCE", "Insurance"),
                            ("MARKETING", "Marketing"),
                            ("WAGES", "Wages"),
                            ("PROFESSIONAL", "Professional Fees"),
                            ("BANK_FEES", "Bank Fees"),
                            ("OFFICE", "Office Expenses"),
                            ("TRAVEL", "Travel"),
                            ("SUPPLIES", "Supplies"),
                            ("EQUIPMENT", "Equipment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expense amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHECK", "Check"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Credit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expense_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_expenses",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("po_number", models.CharField(help_text="Purchase order number", max_length=50)),
                ("supplier_name", models.CharField(help_text="Supplier name", max_length=255)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total purchase amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("SENT", "Sent"),
                            ("RECEIVED", "Received"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_purchase_orders",
                "unique_together": {("tenant", "po_number")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(help_text="Payment reference number", max_length=50),
                ),
                ("supplier_name", models.CharField(help_text="Supplier name", max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHECK", "Check"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Credit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, help_text="Payment description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_payments",
                "unique_together": {("tenant", "payment_number")},
            },
        ),
    ]
