# Generated by Django 4.2.11 on 2025-11-02 09:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0025_add_documentation_models"),
        ("django_ledger", "0016_remove_accountmodel_django_ledg_coa_mod_e19964_idx_and_more"),
        ("accounting", "0004_add_invoice_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Name/description of the bank account", max_length=100
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Bank account number (last 4 digits recommended for security)",
                        max_length=50,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(help_text="Name of the financial institution", max_length=100),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Checking Account"),
                            ("SAVINGS", "Savings Account"),
                            ("MONEY_MARKET", "Money Market Account"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("LINE_OF_CREDIT", "Line of Credit"),
                            ("OTHER", "Other"),
                        ],
                        default="CHECKING",
                        help_text="Type of bank account",
                        max_length=20,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Opening balance when account was added to system",
                        max_digits=12,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current book balance",
                        max_digits=12,
                    ),
                ),
                (
                    "reconciled_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Last reconciled balance",
                        max_digits=12,
                    ),
                ),
                (
                    "last_reconciled_date",
                    models.DateField(
                        blank=True, help_text="Date of last successful reconciliation", null=True
                    ),
                ),
                (
                    "routing_number",
                    models.CharField(blank=True, help_text="Bank routing number", max_length=20),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True,
                        help_text="SWIFT/BIC code for international transfers",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency code (ISO 4217)", max_length=3
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this bank account"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this account is currently active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default bank account for transactions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this bank account",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked django-ledger bank account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jewelry_bank_accounts",
                        to="django_ledger.bankaccountmodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this bank account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "db_table": "accounting_bank_accounts",
                "ordering": ["-is_default", "account_name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="accounting__tenant__df64c2_idx"
                    ),
                    models.Index(
                        fields=["tenant", "account_type"], name="accounting__tenant__1504f9_idx"
                    ),
                    models.Index(fields=["is_default"], name="accounting__is_defa_58ec5c_idx"),
                    models.Index(
                        fields=["last_reconciled_date"], name="accounting__last_re_89cbc0_idx"
                    ),
                ],
                "unique_together": {("tenant", "account_number", "bank_name")},
            },
        ),
    ]
