# Generated by Django 4.2.11 on 2025-11-02 10:21

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ledger", "0016_remove_accountmodel_django_ledg_coa_mod_e19964_idx_and_more"),
        ("core", "0025_add_documentation_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0005_create_bank_account_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reconciliation_date",
                    models.DateField(help_text="Date of the bank statement being reconciled"),
                ),
                (
                    "period_start_date",
                    models.DateField(
                        blank=True, help_text="Start date of reconciliation period", null=True
                    ),
                ),
                (
                    "period_end_date",
                    models.DateField(
                        blank=True, help_text="End date of reconciliation period", null=True
                    ),
                ),
                (
                    "statement_beginning_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Beginning balance from bank statement",
                        max_digits=12,
                    ),
                ),
                (
                    "statement_ending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ending balance from bank statement",
                        max_digits=12,
                    ),
                ),
                (
                    "book_beginning_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Beginning balance from accounting records",
                        max_digits=12,
                    ),
                ),
                (
                    "book_ending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ending balance from accounting records",
                        max_digits=12,
                    ),
                ),
                (
                    "total_deposits",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total deposits reconciled",
                        max_digits=12,
                    ),
                ),
                (
                    "total_withdrawals",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total withdrawals reconciled",
                        max_digits=12,
                    ),
                ),
                (
                    "total_adjustments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total adjustments made during reconciliation",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="IN_PROGRESS",
                        help_text="Current status of reconciliation",
                        max_length=20,
                    ),
                ),
                (
                    "is_balanced",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the reconciliation is balanced (statement = book)",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Difference between statement and book balances",
                        max_digits=12,
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when reconciliation was completed",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this reconciliation"),
                ),
                (
                    "statement_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded bank statement file",
                        null=True,
                        upload_to="bank_statements/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        help_text="Bank account being reconciled",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="accounting.bankaccount",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed this reconciliation",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who started this reconciliation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this reconciliation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_reconciliations",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Reconciliation",
                "verbose_name_plural": "Bank Reconciliations",
                "db_table": "accounting_bank_reconciliations",
                "ordering": ["-reconciliation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "import_date",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time of import"),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original filename of imported statement", max_length=255
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("CSV", "CSV (Comma-Separated Values)"),
                            ("OFX", "OFX (Open Financial Exchange)"),
                            ("QFX", "QFX (Quicken Financial Exchange)"),
                            ("QBO", "QBO (QuickBooks Online)"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Format of the imported file",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded statement file",
                        upload_to="bank_statement_imports/%Y/%m/",
                    ),
                ),
                (
                    "transactions_imported",
                    models.IntegerField(
                        default=0, help_text="Number of transactions imported from file"
                    ),
                ),
                (
                    "transactions_matched",
                    models.IntegerField(
                        default=0, help_text="Number of transactions automatically matched"
                    ),
                ),
                (
                    "transactions_duplicates",
                    models.IntegerField(
                        default=0, help_text="Number of duplicate transactions skipped"
                    ),
                ),
                (
                    "transactions_errors",
                    models.IntegerField(
                        default=0, help_text="Number of transactions that failed to import"
                    ),
                ),
                (
                    "statement_start_date",
                    models.DateField(blank=True, help_text="Start date from statement", null=True),
                ),
                (
                    "statement_end_date",
                    models.DateField(blank=True, help_text="End date from statement", null=True),
                ),
                (
                    "statement_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ending balance from statement",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIALLY_COMPLETED", "Partially Completed"),
                        ],
                        default="PENDING",
                        help_text="Current status of import",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if import failed"),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing started", null=True
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes about this import")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        help_text="Bank account for this import",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_imports",
                        to="accounting.bankaccount",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        help_text="User who performed this import",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_statement_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this import",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statement_imports",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Statement Import",
                "verbose_name_plural": "Bank Statement Imports",
                "db_table": "accounting_bank_statement_imports",
                "ordering": ["-import_date"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("transaction_date", models.DateField(help_text="Date the transaction occurred")),
                (
                    "description",
                    models.CharField(
                        help_text="Transaction description from bank statement", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=12,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit (Money Out)"), ("CREDIT", "Credit (Money In)")],
                        help_text="Whether this is a debit or credit transaction",
                        max_length=10,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Check number, wire reference, or other reference",
                        max_length=50,
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(
                        default=False, help_text="Whether this transaction has been reconciled"
                    ),
                ),
                (
                    "reconciled_date",
                    models.DateField(
                        blank=True, help_text="Date when transaction was reconciled", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes about this transaction"),
                ),
                (
                    "unreconcile_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for unreconciling this transaction (audit trail)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        help_text="Bank account this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.bankaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_bank_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journal entry that matches this bank transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_bank_transactions",
                        to="django_ledger.journalentrymodel",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reconciled this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciled_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reconciliation session this transaction belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="accounting.bankreconciliation",
                    ),
                ),
                (
                    "statement_import",
                    models.ForeignKey(
                        blank=True,
                        help_text="Import session that created this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_transactions",
                        to="accounting.bankstatementimport",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Transaction",
                "verbose_name_plural": "Bank Transactions",
                "db_table": "accounting_bank_transactions",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "bank_account", "transaction_date"],
                        name="accounting__tenant__d85fc5_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_reconciled"], name="accounting__tenant__bf1cf6_idx"
                    ),
                    models.Index(
                        fields=["transaction_date"], name="accounting__transac_a5232c_idx"
                    ),
                    models.Index(fields=["reconciliation"], name="accounting__reconci_4c5817_idx"),
                    models.Index(
                        fields=["matched_journal_entry"], name="accounting__matched_70b4e3_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="bankstatementimport",
            index=models.Index(
                fields=["tenant", "bank_account", "import_date"],
                name="accounting__tenant__1becc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementimport",
            index=models.Index(fields=["tenant", "status"], name="accounting__tenant__1011a1_idx"),
        ),
        migrations.AddIndex(
            model_name="bankstatementimport",
            index=models.Index(fields=["import_date"], name="accounting__import__30335f_idx"),
        ),
        migrations.AddIndex(
            model_name="bankstatementimport",
            index=models.Index(fields=["status"], name="accounting__status_74f4f3_idx"),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["tenant", "bank_account", "reconciliation_date"],
                name="accounting__tenant__d420da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(fields=["tenant", "status"], name="accounting__tenant__4bd1b9_idx"),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["reconciliation_date"], name="accounting__reconci_771cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["status", "is_balanced"], name="accounting__status_93810d_idx"
            ),
        ),
    ]
