# Generated by Django 4.2.11 on 2025-11-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ledger", "0016_remove_accountmodel_django_ledg_coa_mod_e19964_idx_and_more"),
        ("accounting", "0006_bankreconciliation_bankstatementimport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="gl_account",
            field=models.ForeignKey(
                blank=True,
                help_text="General Ledger account this bank account represents (e.g., 1001 - Cash)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_accounts",
                to="django_ledger.accountmodel",
            ),
        ),
    ]
