# Generated by Django 4.2.11 on 2025-11-03 06:58

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0025_add_documentation_models"),
        ("django_ledger", "0016_remove_accountmodel_django_ledg_coa_mod_e19964_idx_and_more"),
        ("accounting", "0008_add_balance_fields_to_bankaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetDisposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("disposal_date", models.DateField(help_text="Date when asset was disposed")),
                (
                    "disposal_method",
                    models.CharField(
                        choices=[
                            ("SOLD", "Sold"),
                            ("SCRAPPED", "Scrapped"),
                            ("DONATED", "Donated"),
                            ("TRADED", "Traded In"),
                            ("LOST", "Lost/Stolen"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Method of disposal",
                        max_length=20,
                    ),
                ),
                (
                    "proceeds",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount received from disposal (if sold)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "book_value_at_disposal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Book value of asset at time of disposal",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "gain_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gain or loss on disposal (proceeds - book value)",
                        max_digits=12,
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True, help_text="Name of buyer (if sold)", max_length=200
                    ),
                ),
                ("disposal_reason", models.TextField(blank=True, help_text="Reason for disposal")),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes about the disposal"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asset Disposal",
                "verbose_name_plural": "Asset Disposals",
                "db_table": "accounting_asset_disposals",
                "ordering": ["-disposal_date"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period_date",
                    models.DateField(
                        help_text="Date of the depreciation period (typically month-end)"
                    ),
                ),
                ("period_month", models.IntegerField(help_text="Month number (1-12)")),
                ("period_year", models.IntegerField(help_text="Year")),
                (
                    "depreciation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Depreciation amount for this period",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total accumulated depreciation after this period",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "book_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Book value after this period's depreciation",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this depreciation entry"),
                ),
                (
                    "is_adjustment",
                    models.BooleanField(
                        default=False, help_text="Whether this is an adjustment entry"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Depreciation Schedule",
                "verbose_name_plural": "Depreciation Schedules",
                "db_table": "accounting_depreciation_schedules",
                "ordering": ["-period_date"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(help_text="Name/description of the asset", max_length=200),
                ),
                (
                    "asset_number",
                    models.CharField(help_text="Unique asset identification number", max_length=50),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EQUIPMENT", "Equipment"),
                            ("FIXTURES", "Fixtures"),
                            ("FURNITURE", "Furniture"),
                            ("VEHICLES", "Vehicles"),
                            ("BUILDINGS", "Buildings"),
                            ("COMPUTERS", "Computers & IT Equipment"),
                            ("TOOLS", "Tools"),
                            ("OTHER", "Other"),
                        ],
                        default="EQUIPMENT",
                        help_text="Category of the asset",
                        max_length=50,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, help_text="Manufacturer's serial number", max_length=100
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Manufacturer or brand name", max_length=100
                    ),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, help_text="Model number", max_length=100),
                ),
                ("acquisition_date", models.DateField(help_text="Date when asset was acquired")),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original cost of the asset",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Estimated salvage/residual value at end of useful life",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "useful_life_months",
                    models.IntegerField(
                        help_text="Useful life in months",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[
                            ("STRAIGHT_LINE", "Straight Line"),
                            ("DECLINING_BALANCE", "Declining Balance"),
                            ("UNITS_OF_PRODUCTION", "Units of Production"),
                        ],
                        default="STRAIGHT_LINE",
                        help_text="Method used to calculate depreciation",
                        max_length=30,
                    ),
                ),
                (
                    "depreciation_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Depreciation rate for declining balance method (e.g., 200 for double declining)",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISPOSED", "Disposed"),
                            ("FULLY_DEPRECIATED", "Fully Depreciated"),
                        ],
                        default="ACTIVE",
                        help_text="Current status of the asset",
                        max_length=20,
                    ),
                ),
                (
                    "current_book_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current book value (cost - accumulated depreciation)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total depreciation accumulated to date",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "last_depreciation_date",
                    models.DateField(
                        blank=True, help_text="Date of last depreciation calculation", null=True
                    ),
                ),
                (
                    "asset_account",
                    models.CharField(
                        help_text="GL account code for the asset (e.g., 1500 - Equipment)",
                        max_length=20,
                    ),
                ),
                (
                    "accumulated_depreciation_account",
                    models.CharField(
                        help_text="GL account code for accumulated depreciation (e.g., 1510 - Accumulated Depreciation)",
                        max_length=20,
                    ),
                ),
                (
                    "depreciation_expense_account",
                    models.CharField(
                        help_text="GL account code for depreciation expense (e.g., 6500 - Depreciation Expense)",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Physical location of the asset", max_length=200
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department responsible for the asset", max_length=100
                    ),
                ),
                (
                    "purchase_order_number",
                    models.CharField(
                        blank=True, help_text="Purchase order number for acquisition", max_length=50
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, help_text="Vendor/supplier of the asset", max_length=200
                    ),
                ),
                (
                    "warranty_expiration",
                    models.DateField(blank=True, help_text="Warranty expiration date", null=True),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes about this asset"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fixed Asset",
                "verbose_name_plural": "Fixed Assets",
                "db_table": "accounting_fixed_assets",
                "ordering": ["asset_number"],
            },
        ),
        migrations.RemoveIndex(
            model_name="bankaccount",
            name="accounting__last_re_idx",
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for this asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who registered this asset",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_fixed_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this fixed asset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixed_assets",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="depreciationschedule",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this depreciation entry",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_depreciation_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="depreciationschedule",
            name="fixed_asset",
            field=models.ForeignKey(
                help_text="Fixed asset this depreciation applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depreciation_schedules",
                to="accounting.fixedasset",
            ),
        ),
        migrations.AddField(
            model_name="depreciationschedule",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Journal entry created for this depreciation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="depreciation_schedules",
                to="django_ledger.journalentrymodel",
            ),
        ),
        migrations.AddField(
            model_name="depreciationschedule",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this depreciation record",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depreciation_schedules",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who recorded this disposal",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_asset_disposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="fixed_asset",
            field=models.OneToOneField(
                help_text="Fixed asset being disposed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disposal",
                to="accounting.fixedasset",
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Journal entry created for this disposal",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asset_disposals",
                to="django_ledger.journalentrymodel",
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this disposal record",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_disposals",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(fields=["tenant", "status"], name="accounting__tenant__30909b_idx"),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["tenant", "category"], name="accounting__tenant__bbee1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(fields=["acquisition_date"], name="accounting__acquisi_5bec6b_idx"),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["last_depreciation_date"], name="accounting__last_de_56f0c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["status", "last_depreciation_date"], name="accounting__status_b9bfe7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fixedasset",
            unique_together={("tenant", "asset_number")},
        ),
        migrations.AddIndex(
            model_name="depreciationschedule",
            index=models.Index(
                fields=["tenant", "period_date"], name="accounting__tenant__6b34d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depreciationschedule",
            index=models.Index(
                fields=["fixed_asset", "period_date"], name="accounting__fixed_a_7e26c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depreciationschedule",
            index=models.Index(
                fields=["period_year", "period_month"], name="accounting__period__c7fc7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depreciationschedule",
            index=models.Index(fields=["journal_entry"], name="accounting__journal_5cfe66_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="depreciationschedule",
            unique_together={("fixed_asset", "period_date")},
        ),
        migrations.AddIndex(
            model_name="assetdisposal",
            index=models.Index(
                fields=["tenant", "disposal_date"], name="accounting__tenant__6e8565_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetdisposal",
            index=models.Index(fields=["fixed_asset"], name="accounting__fixed_a_4869a0_idx"),
        ),
        migrations.AddIndex(
            model_name="assetdisposal",
            index=models.Index(fields=["disposal_method"], name="accounting__disposa_35e743_idx"),
        ),
        migrations.AddIndex(
            model_name="assetdisposal",
            index=models.Index(fields=["journal_entry"], name="accounting__journal_1401eb_idx"),
        ),
    ]
