# Generated by Django 4.2.26 on 2025-12-09 17:33

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0032_update_plans_with_comprehensive_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the discount rule",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_period_months",
                    models.IntegerField(
                        choices=[
                            (1, "1 Month"),
                            (3, "3 Months"),
                            (6, "6 Months"),
                            (12, "12 Months (1 Year)"),
                        ],
                        help_text="Number of months for this billing period",
                        unique=True,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount percentage (0-100) for this billing period",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description (e.g., 'Save 10% with 3-month billing')",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this discount rule is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the discount rule was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the discount rule was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Discount",
                "verbose_name_plural": "Subscription Discounts",
                "db_table": "subscription_discounts",
                "ordering": ["billing_period_months"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the purchase",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("new", "New Subscription"),
                            ("renewal", "Renewal"),
                            ("upgrade", "Plan Upgrade"),
                            ("downgrade", "Plan Downgrade"),
                        ],
                        default="new",
                        help_text="Type of purchase (new, renewal, upgrade, downgrade)",
                        max_length=20,
                    ),
                ),
                (
                    "billing_period_months",
                    models.IntegerField(
                        choices=[
                            (1, "1 Month"),
                            (3, "3 Months"),
                            (6, "6 Months"),
                            (12, "12 Months (1 Year)"),
                        ],
                        default=1,
                        help_text="Billing period in months",
                    ),
                ),
                ("start_date", models.DateField(help_text="Start date of the subscription period")),
                ("end_date", models.DateField(help_text="End date of the subscription period")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price before discount (plan price × months)",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount percentage applied",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount amount in base currency",
                        max_digits=12,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Final price after discount", max_digits=12
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("IRR", "Iranian Rial"),
                            ("EUR", "Euro"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("USDT", "USDT"),
                        ],
                        default="USD",
                        help_text="Currency for the transaction",
                        max_length=5,
                    ),
                ),
                (
                    "base_price_irr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Base price in Iranian Rial (Toman × 10)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "final_price_irr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Final price in Iranian Rial",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current payment status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("placeholder", "Test/Development"),
                            ("bank_transfer_iran", "Iranian Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("stripe", "Credit/Debit Card (Stripe)"),
                            ("crypto_btc", "Bitcoin"),
                            ("crypto_eth", "Ethereum"),
                            ("crypto_usdt", "USDT (Tether)"),
                        ],
                        default="placeholder",
                        help_text="Selected payment method",
                        max_length=30,
                    ),
                ),
                (
                    "payment_gateway_transaction_id",
                    models.CharField(
                        blank=True, help_text="Transaction ID from payment gateway", max_length=255
                    ),
                ),
                (
                    "payment_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when payment was completed", null=True
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Unique invoice number (e.g., INV-20251209-ABC123)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "invoice_pdf_path",
                    models.CharField(
                        blank=True, help_text="Path to generated invoice PDF", max_length=500
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (gateway responses, etc.)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the purchaser", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent string of the purchaser", max_length=500
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes about this purchase"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the purchase was initiated"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the purchase was last updated"
                    ),
                ),
                (
                    "previous_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous plan (for upgrades/downgrades)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upgrade_from_purchases",
                        to="core.subscriptionplan",
                    ),
                ),
                (
                    "purchased_by",
                    models.ForeignKey(
                        help_text="User who initiated the purchase",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        help_text="Subscription plan being purchased",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="core.subscriptionplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant making the purchase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_purchases",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Purchase",
                "verbose_name_plural": "Subscription Purchases",
                "db_table": "subscription_purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the transaction",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Unique transaction identifier", unique=True
                    ),
                ),
                (
                    "payment_gateway",
                    models.CharField(
                        help_text="Payment gateway used (e.g., 'paypal', 'stripe', 'crypto')",
                        max_length=50,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from the payment gateway",
                        max_length=255,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="Additional gateway reference/tracking number",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Transaction amount", max_digits=12
                    ),
                ),
                ("currency", models.CharField(help_text="Transaction currency", max_length=5)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Exchange rate used (for crypto/IRR conversions)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Current transaction status",
                        max_length=20,
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Request data sent to gateway"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Response data from gateway"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if transaction failed"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, help_text="Error code from gateway", max_length=100
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Attempt number for this transaction"
                    ),
                ),
                (
                    "is_retry",
                    models.BooleanField(default=False, help_text="Whether this is a retry attempt"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address during transaction", null=True
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when transaction was initiated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when transaction completed", null=True
                    ),
                ),
                (
                    "subscription_purchase",
                    models.ForeignKey(
                        help_text="Associated subscription purchase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.subscriptionpurchase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant for RLS enforcement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payment_transactions",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionpurchase",
            index=models.Index(
                fields=["tenant", "payment_status"], name="purchase_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpurchase",
            index=models.Index(fields=["payment_status"], name="purchase_payment_status_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionpurchase",
            index=models.Index(fields=["invoice_number"], name="purchase_invoice_number_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionpurchase",
            index=models.Index(fields=["created_at"], name="purchase_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionpurchase",
            index=models.Index(
                fields=["payment_method", "payment_status"], name="purchase_method_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["tenant", "status"], name="tx_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["transaction_id"], name="tx_transaction_id_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["gateway_transaction_id"], name="tx_gateway_id_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["status"], name="tx_status_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["initiated_at"], name="tx_initiated_at_idx"),
        ),
    ]
