# Generated by Django 4.2.11 on 2025-10-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_add_inventory_transfer_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="display_order",
            field=models.IntegerField(default=0, help_text="Display order for sorting categories"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Category image", null=True, upload_to="category_images/"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="meta_description",
            field=models.TextField(blank=True, help_text="SEO meta description"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="meta_title",
            field=models.CharField(blank=True, help_text="SEO meta title", max_length=200),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="URL-friendly slug for the category", max_length=120
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(fields=["tenant", "slug"], name="cat_tenant_slug_idx"),
        ),
    ]
