# Generated by Django 4.2.11 on 2025-11-01 19:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_giftcardtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Maximum credit allowed for this customer",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="exemption_certificate",
            field=models.FileField(
                blank=True,
                help_text="Tax exemption certificate document",
                upload_to="customer_tax_exemptions/",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(
                default="NET30",
                help_text="Default payment terms (e.g., NET30, NET60, COD)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_exempt",
            field=models.BooleanField(
                default=False, help_text="Whether customer is exempt from sales tax"
            ),
        ),
    ]
