#!/usr/bin/env python3
"""
Generate secure secrets for production deployment.

This script generates cryptographically secure secrets for:
- Django SECRET_KEY
- BACKUP_ENCRYPTION_KEY
- FIELD_ENCRYPTION_KEY
- Database passwords
- Redis password

Usage:
    python scripts/generate_secrets.py
    python scripts/generate_secrets.py --output .env.production
"""

import argparse
import secrets
import string
from base64 import urlsafe_b64encode
from pathlib import Path


def generate_django_secret_key(length=50):
    """Generate a Django SECRET_KEY (avoiding $ to prevent shell interpolation)."""
    chars = string.ascii_letters + string.digits + "!@#%^&*(-_=+)"
    return "".join(secrets.choice(chars) for _ in range(length))


def generate_encryption_key():
    """Generate a Fernet encryption key (32 bytes, base64 encoded)."""
    return urlsafe_b64encode(secrets.token_bytes(32)).decode("utf-8")


def generate_password(length=32):
    """Generate a strong password."""
    chars = string.ascii_letters + string.digits + "!@#$%^&*-_=+"
    return "".join(secrets.choice(chars) for _ in range(length))


def generate_api_key(length=64):
    """Generate an API key."""
    return secrets.token_urlsafe(length)


def main():
    parser = argparse.ArgumentParser(description="Generate secure secrets for production")
    parser.add_argument("--output", "-o", help="Output file path (optional)")
    parser.add_argument("--format", choices=["env", "json"], default="env", help="Output format")
    args = parser.parse_args()

    # Generate all secrets
    secrets_dict = {
        "DJANGO_SECRET_KEY": generate_django_secret_key(50),
        "BACKUP_ENCRYPTION_KEY": generate_encryption_key(),
        "FIELD_ENCRYPTION_KEY": generate_encryption_key(),
        "POSTGRES_PASSWORD": generate_password(32),
        "APP_DB_PASSWORD": generate_password(32),
        "REDIS_PASSWORD": generate_password(32),
        "GRAFANA_ADMIN_PASSWORD": generate_password(24),
    }

    # Print to console
    print("=" * 80)
    print("GENERATED SECRETS - SAVE THESE SECURELY!")
    print("=" * 80)
    print()

    if args.format == "env":
        for key, value in secrets_dict.items():
            print(f"{key}={value}")
    elif args.format == "json":
        import json

        print(json.dumps(secrets_dict, indent=2))

    print()
    print("=" * 80)
    print("IMPORTANT:")
    print("1. Save these secrets in a secure password manager")
    print("2. Never commit these to version control")
    print("3. Use different secrets for each environment")
    print("4. Rotate secrets regularly (every 90 days recommended)")
    print("=" * 80)

    # Optionally write to file
    if args.output:
        output_path = Path(args.output)
        if output_path.exists():
            response = input(f"\n{output_path} already exists. Overwrite? (yes/no): ")
            if response.lower() != "yes":
                print("Aborted.")
                return

        with open(output_path, "w") as f:
            f.write("# Generated secrets - DO NOT COMMIT TO VERSION CONTROL\n")
            f.write("# Generated by scripts/generate_secrets.py\n\n")
            for key, value in secrets_dict.items():
                f.write(f"{key}={value}\n")

        print(f"\nSecrets written to: {output_path}")
        print(f"Remember to set file permissions: chmod 600 {output_path}")


if __name__ == "__main__":
    main()
