# Generated by Django 4.2.11 on 2025-10-24 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this template", max_length=100, unique=True
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("LOW_STOCK", "Low Stock Alert"),
                            ("PAYMENT_REMINDER", "Payment Reminder"),
                            ("ORDER_STATUS", "Order Status Update"),
                            ("SYSTEM", "System Notification"),
                            ("PROMOTION", "Promotion"),
                            ("APPOINTMENT", "Appointment Reminder"),
                        ],
                        help_text="Type of notification this template is for",
                        max_length=20,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Template for notification title (supports Django template syntax)",
                        max_length=255,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Template for notification message (supports Django template syntax)"
                    ),
                ),
                (
                    "action_text_template",
                    models.CharField(
                        blank=True,
                        help_text="Template for action button text",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "action_url_template",
                    models.CharField(
                        blank=True, help_text="Template for action URL", max_length=500, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active and can be used"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this template was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this template was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notifications_template",
                "indexes": [
                    models.Index(
                        fields=["notification_type", "is_active"],
                        name="notif_template_type_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("LOW_STOCK", "Low Stock Alert"),
                            ("PAYMENT_REMINDER", "Payment Reminder"),
                            ("ORDER_STATUS", "Order Status Update"),
                            ("SYSTEM", "System Notification"),
                            ("PROMOTION", "Promotion"),
                            ("APPOINTMENT", "Appointment Reminder"),
                        ],
                        help_text="Type of notification this preference applies to",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App Notification"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                        ],
                        help_text="Notification delivery channel",
                        max_length=10,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this notification type is enabled for this channel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this preference was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this preference was last updated"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet hours (no notifications sent)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, help_text="End of quiet hours", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notifications_preference",
                "indexes": [
                    models.Index(
                        fields=["user", "notification_type"], name="notif_pref_user_type_idx"
                    ),
                    models.Index(fields=["user", "is_enabled"], name="notif_pref_user_enabled_idx"),
                ],
                "unique_together": {("user", "notification_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Notification title/subject", max_length=255)),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("LOW_STOCK", "Low Stock Alert"),
                            ("PAYMENT_REMINDER", "Payment Reminder"),
                            ("ORDER_STATUS", "Order Status Update"),
                            ("SYSTEM", "System Notification"),
                            ("PROMOTION", "Promotion"),
                            ("APPOINTMENT", "Appointment Reminder"),
                        ],
                        default="INFO",
                        help_text="Type of notification for styling and filtering",
                        max_length=20,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the user has read this notification"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notification was created"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When the notification was marked as read", null=True
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to navigate to when notification is clicked",
                        null=True,
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        help_text='Text for action button (e.g., "View Order", "Update Inventory")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this notification expires and should be hidden",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="notif_user_created_idx"),
                    models.Index(
                        fields=["user", "is_read", "-created_at"], name="notif_user_read_idx"
                    ),
                    models.Index(
                        fields=["user", "notification_type", "-created_at"],
                        name="notif_user_type_idx",
                    ),
                    models.Index(fields=["expires_at"], name="notif_expires_idx"),
                ],
            },
        ),
    ]
