# Generated by Django 4.2.11 on 2025-10-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emailtemplate_emailnotification_emailcampaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INFO", "Information"),
                    ("SUCCESS", "Success"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("LOW_STOCK", "Low Stock Alert"),
                    ("PAYMENT_REMINDER", "Payment Reminder"),
                    ("ORDER_STATUS", "Order Status Update"),
                    ("SYSTEM", "System Notification"),
                    ("PROMOTION", "Promotion"),
                    ("APPOINTMENT", "Appointment Reminder"),
                    ("TRANSACTIONAL", "Transactional Email"),
                    ("MARKETING", "Marketing Email"),
                ],
                default="INFO",
                help_text="Type of notification for styling and filtering",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INFO", "Information"),
                    ("SUCCESS", "Success"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("LOW_STOCK", "Low Stock Alert"),
                    ("PAYMENT_REMINDER", "Payment Reminder"),
                    ("ORDER_STATUS", "Order Status Update"),
                    ("SYSTEM", "System Notification"),
                    ("PROMOTION", "Promotion"),
                    ("APPOINTMENT", "Appointment Reminder"),
                    ("TRANSACTIONAL", "Transactional Email"),
                    ("MARKETING", "Marketing Email"),
                ],
                help_text="Type of notification this preference applies to",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INFO", "Information"),
                    ("SUCCESS", "Success"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("LOW_STOCK", "Low Stock Alert"),
                    ("PAYMENT_REMINDER", "Payment Reminder"),
                    ("ORDER_STATUS", "Order Status Update"),
                    ("SYSTEM", "System Notification"),
                    ("PROMOTION", "Promotion"),
                    ("APPOINTMENT", "Appointment Reminder"),
                    ("TRANSACTIONAL", "Transactional Email"),
                    ("MARKETING", "Marketing Email"),
                ],
                help_text="Type of notification this template is for",
                max_length=20,
            ),
        ),
    ]
